### ISSUE TITLE
[FEATURE] Cloud OTA Update Project Proposal

### ISSUE THREAD

**Issue by MarkDing** [MarkDing/IoT-Developer-Boot-Camp-Wiki#36]
**Describe the new feature you'd like**
Victor and I came into a new article on creating the easy understanding OTA article. In the real situation. The end device at home and the update firmware was drag into the web interface and push to the cloud. There is a gateway at home to dispatch the firmware to the end device. In our implementation. We would like to choose Laptop + NCP as a bridge between the cloud and end device. Running a GUI tool on the laptop, connect to the cloud to get the OTA file and send it to end device via the NCP device. It is an easy understandable way and close to the real use case. The GUI tool only show device type no matter what protocol it is. Like Light, Door Lock, Sensor, etc. The NCP can pileup the Zigbee/Bluetooth/Proprietary image file together. Or doing the dynamic programming during the OTA process. 

![image](https://user-images.githubusercontent.com/1233397/72146130-ca673200-33d6-11ea-8719-ff6876b12ea7.png)

**Comment by hoo-way** [comment]
The topology: Device -- User -- Vendor

**Comment by MarkDing** [comment]
The concepts of the idea look good to us. Let's get started the project with the proposal.
