### ISSUE TITLE
[DOC] Prepare Chinese version of Zigbee Boot Camp hands-on documentations.

### ISSUE THREAD

**Issue by ChengYuan-CY** [MarkDing/IoT-Developer-Boot-Camp-Wiki#55]
**Describe the request**
We have a Zigbee Boot camp project to provide a quick start guide for those customer who are really new on our Zigbee product, however, currently we have only English version documentations. It’s not much readable for Chinese engineer. 

**Recommended improvement**
Translate the hands-on documentations.

**Comment by MarkDing** [comment]
The Chinese version has been finished by a whole team work.
